# Generated by Django 5.2.4 on 2025-08-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.PositiveIntegerField()),
                ('index_number', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Germany', max_length=50)),
            ],
            options={
                'verbose_name': 'Apartment Address',
                'verbose_name_plural': 'Apartment Addresses',
                'db_table': 'apartment_address',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category_apartments',
            },
        ),
        migrations.CreateModel(
            name='FederalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Federal State',
                'verbose_name_plural': 'Federal States',
                'db_table': 'federal_state',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.DecimalField(decimal_places=1, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments', to='accounts.landlorduser')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='apartments.apartmentaddress')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='apartments.category')),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
                'db_table': 'apartment',
                'ordering': ['-booking_count'],
            },
        ),
        migrations.AddField(
            model_name='apartmentaddress',
            name='federal_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_addresses', to='apartments.federalstate'),
        ),
    ]
