# Generated by Django 5.2.4 on 2025-08-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentaddress',
            name='house_number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='apartmentaddress',
            name='index_number',
            field=models.CharField(max_length=5),
        ),
    ]
