# Generated by Django 5.2.4 on 2025-08-12 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_birthday'),
        ('apartments', '0002_alter_apartmentaddress_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='accounts.landlorduser'),
        ),
    ]
