# Generated by Django 5.2.4 on 2025-08-12 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_birthday'),
        ('bookings', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', 'Very poor'), ('2', 'Poor'), ('3', 'Average'), ('4', 'Good'), ('5', 'Excellent')], max_length=10)),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='accounts.tenantuser')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'review',
                'constraints': [models.UniqueConstraint(fields=('booking',), name='unique_booking_review')],
            },
        ),
    ]
