# Generated by Django 5.2.4 on 2025-08-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
    ]
